// <auto-generated />
namespace DAGStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ReCreateColumnSliderID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReCreateColumnSliderID));
        
        string IMigrationMetadata.Id
        {
            get { return "202211081105485_ReCreate-Column-SliderID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
